name: Check Code Formatting
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check-formatting:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Install dependencies
      - name: Install Dependencies
        run: yarn install

      # Run the Prettier
      - name: Run Prettier Check
        run: yarn format:check
